### ISSUE TITLE
NPC A

### ISSUE THREAD

**Issue by KNG-Scherezade** [KNG-Scherezade/COMP-476-Project#34]
NPC Movement Behaviour | NPC A
-- | --
Can Detect Traps | No
Can Disarm Traps | No
Wander Behaviour | Set of nodes
Chase Behaviour | Prioritize player
Group Behaviour | Swarm Behaviour
Alert Level Behaviour | Short Memory
Decision making |  
Communication behaviour | Listen only(Nathan)
Attack Method | Charge

**Comment by ECHibiki** [comment]
Divides into multiple sections that can be worked on
