### ISSUE TITLE
NPC B

### ISSUE THREAD

**Issue by KNG-Scherezade** [KNG-Scherezade/COMP-476-Project#35]
NPC B
--
Yes
No
Set of nodes
Prioritize player
Swarm Behaviour
Check adjacent rooms
 
Nofity A of player, notify C of traps
Charge (add shoot if we have time)

NPC Movement Behaviour | NPC B
-- | --
Can Detect Traps | Yes
Can Disarm Traps | No
Wander Behaviour | Set of nodes
Chase Behaviour | Prioritize player
Group Behaviour | Swarm Behaviour
Alert Level Behaviour | Check adjacent rooms
Decision making |  
Communication behaviour | Nofity A of player, notify C of traps
Attack Method | Charge (add shoot if we have time)

**Comment by ECHibiki** [comment]
Divides into multiple sections that can be worked on
