### ISSUE TITLE
NPC C

### ISSUE THREAD

**Issue by KNG-Scherezade** [KNG-Scherezade/COMP-476-Project#36]
NPC Movement Behaviour | NPC C
-- | --
Can Detect Traps | Yes
Can Disarm Traps | Yes
Wander Behaviour | Random wander
Chase Behaviour | Prioritize traps
Group Behaviour | Swarm Behaviour
Alert Level Behaviour | Inspects doors and obstructions
Decision making |  
Communication behaviour | Notify B and A of player, update waypoints
Attack Method | Notify

**Comment by ECHibiki** [comment]
Divides into multiple sections that can be worked on
