### ISSUE TITLE
Gameplay Map(basic aspects)

### ISSUE THREAD

**Issue by KNG-Scherezade** [KNG-Scherezade/COMP-476-Project#38]
Basic map that will be built upon as time goes on

**Comment by ECHibiki** [comment]
Will acquire the assets and make a basic flat plain in our main game scene

**Comment by ECHibiki** [comment]
Test map set up and some corridor prefabs

**Comment by ECHibiki** [comment]
Going to add my Assignment2 Map and build some prefabs for this so that map construction is simple
